// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type UserInfoRequest struct {
	Identity string `json:"identity"`
}

type UserInfoResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type MailCaptchaRequest struct {
	Email string `json:"email"`
}

type MailCaptchaResponse struct {
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
}

type UserRegisterResponse struct {
}
